export const THEMES = [
  {
    id: "thermal-dark",
    label: "Thermal Dark",
    emoji: "\uD83D\uDD25",
    accent: "#F97316",
    mode: "dark",
    description: "Dark theme with heat-inspired orange accents. Best for night work.",
    tags: ["Dark Mode", "High Contrast"],
    preview: {
      bg: "#09090B",
      sidebar: "#18181B",
      topbar: "#18181B",
      card1: "#F97316",
      card2: "#EA580C",
      card3: "#27272A",
      text: "#FAFAFA",
      muted: "#71717A",
    },
  },
  {
    id: "arctic-light",
    label: "Arctic Light",
    emoji: "\u2744\uFE0F",
    accent: "#0EA5E9",
    mode: "light",
    description: "Clean light theme with sky blue accents. Ideal for daytime operations.",
    tags: ["Light Mode", "Crisp"],
    preview: {
      bg: "#F8FAFC",
      sidebar: "#FFFFFF",
      topbar: "#FFFFFF",
      card1: "#0EA5E9",
      card2: "#0284C7",
      card3: "#F1F5F9",
      text: "#0F172A",
      muted: "#94A3B8",
    },
  },
  {
    id: "midnight-blue",
    label: "Midnight Blue",
    emoji: "\uD83C\uDF19",
    accent: "#3B82F6",
    mode: "dark",
    description: "Deep navy with blue accents. Calm and professional for command centers.",
    tags: ["Dark Mode", "Professional"],
    preview: {
      bg: "#0D1117",
      sidebar: "#161B22",
      topbar: "#161B22",
      card1: "#3B82F6",
      card2: "#2563EB",
      card3: "#21262D",
      text: "#E2E8F0",
      muted: "#8B949E",
    },
  },
  {
    id: "forest-ops",
    label: "Forest Ops",
    emoji: "\uD83C\uDF32",
    accent: "#22C55E",
    mode: "dark",
    description: "Military-grade dark green theme. Built for outdoor field operations.",
    tags: ["Dark Mode", "Field Ops"],
    preview: {
      bg: "#0A1628",
      sidebar: "#0F1F35",
      topbar: "#0F1F35",
      card1: "#22C55E",
      card2: "#16A34A",
      card3: "#162A45",
      text: "#DCFCE7",
      muted: "#4ADE80",
    },
  },
  {
    id: "volcanic-red",
    label: "Volcanic Red",
    emoji: "\uD83C\uDF0B",
    accent: "#EF4444",
    mode: "dark",
    description: "Intense dark red theme. High urgency for critical monitoring.",
    tags: ["Dark Mode", "Alert Focus"],
    preview: {
      bg: "#110808",
      sidebar: "#1C0E0E",
      topbar: "#1C0E0E",
      card1: "#EF4444",
      card2: "#DC2626",
      card3: "#2A1414",
      text: "#FEF2F2",
      muted: "#F87171",
    },
  },
  {
    id: "cyber-purple",
    label: "Cyber Purple",
    emoji: "\u26A1",
    accent: "#A855F7",
    mode: "dark",
    description: "Neon purple on deep space. Futuristic aesthetic for tech-forward teams.",
    tags: ["Dark Mode", "Futuristic"],
    preview: {
      bg: "#0D0D1A",
      sidebar: "#13132A",
      topbar: "#13132A",
      card1: "#A855F7",
      card2: "#9333EA",
      card3: "#1C1C3A",
      text: "#F3E8FF",
      muted: "#C084FC",
    },
  },
  {
    id: "amber-warning",
    label: "Amber Warning",
    emoji: "\u26A0\uFE0F",
    accent: "#F59E0B",
    mode: "dark",
    description: "Amber-gold on dark. Command attention for safety-critical dashboards.",
    tags: ["Dark Mode", "Safety"],
    preview: {
      bg: "#111009",
      sidebar: "#1C1A0E",
      topbar: "#1C1A0E",
      card1: "#F59E0B",
      card2: "#D97706",
      card3: "#2A2614",
      text: "#FFFBEB",
      muted: "#FCD34D",
    },
  },
  {
    id: "rose-gold",
    label: "Rose Gold",
    emoji: "\uD83C\uDF39",
    accent: "#F43F5E",
    mode: "dark",
    description: "Elegant rose accents on warm dark. Refined for executive dashboards.",
    tags: ["Dark Mode", "Elegant"],
    preview: {
      bg: "#1A0F0F",
      sidebar: "#251515",
      topbar: "#251515",
      card1: "#F43F5E",
      card2: "#E11D48",
      card3: "#321C1C",
      text: "#FFF1F2",
      muted: "#FB7185",
    },
  },
  {
    id: "slate-pro",
    label: "Slate Pro",
    emoji: "\uD83D\uDCDD",
    accent: "#6366F1",
    mode: "light",
    description: "Neutral light with indigo accents. Clean and distraction-free.",
    tags: ["Light Mode", "Minimal"],
    preview: {
      bg: "#F1F5F9",
      sidebar: "#FFFFFF",
      topbar: "#FFFFFF",
      card1: "#6366F1",
      card2: "#4F46E5",
      card3: "#E2E8F0",
      text: "#1E293B",
      muted: "#64748B",
    },
  },
  {
    id: "terminal-green",
    label: "Terminal Green",
    emoji: "\uD83D\uDCBB",
    accent: "#4ADE80",
    mode: "dark",
    description: "Retro matrix-style green on black. For the hacker in all of us.",
    tags: ["Dark Mode", "Retro"],
    preview: {
      bg: "#020C02",
      sidebar: "#061406",
      topbar: "#061406",
      card1: "#4ADE80",
      card2: "#22C55E",
      card3: "#0A1F0A",
      text: "#DCFCE7",
      muted: "#4ADE80",
    },
  },
] as const

export type ThemeId = (typeof THEMES)[number]["id"]

export const DEFAULT_THEME: ThemeId = "thermal-dark"
export const STORAGE_KEY = "echoheat-theme"
export const A11Y_STORAGE_KEY = "echoheat-a11y"
